// <auto-generated />
using System;
using BookStore.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookStore.Data.Migrations
{
    [DbContext(typeof(bsDbContext))]
    partial class bsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookStore.Data.Entities.AppConfig", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("AppConfigs");

                    b.HasData(
                        new
                        {
                            Key = "HomeTitle",
                            Value = "This is home page of eShopSolution"
                        },
                        new
                        {
                            Key = "HomeKeyword",
                            Value = "This is keyword of eShopSolution"
                        },
                        new
                        {
                            Key = "HomeDescription",
                            Value = "This is description of eShopSolution"
                        });
                });

            modelBuilder.Entity("BookStore.Data.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4965cc8-fdab-433f-ae1d-79540827db5a"),
                            ConcurrencyStamp = "aa9b33dc-eaed-4aef-9120-68d694b2b445",
                            Description = "Administrator Role",
                            Name = "admin",
                            NormalizedName = "admin"
                        },
                        new
                        {
                            Id = new Guid("90057ee3-511a-4de1-94c2-93898f1018d9"),
                            ConcurrencyStamp = "ff8b53de-9a94-46a6-a914-56301f46a356",
                            Description = "User Role",
                            Name = "user",
                            NormalizedName = "user"
                        });
                });

            modelBuilder.Entity("BookStore.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FisrtName")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1cee3d50-87bb-48d5-a493-376829c581c9"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7278ad41-e9fe-448b-835a-d8bb9eec0f42",
                            Dob = new DateTime(2000, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "danglong136i@gmail.com",
                            EmailConfirmed = true,
                            FisrtName = "Long",
                            LastName = "Dang",
                            LockoutEnabled = false,
                            NormalizedEmail = "danglong136i@gmail.com",
                            NormalizedUserName = "admin",
                            PasswordHash = "AQAAAAEAACcQAAAAEO5XKr7WREkDdqiY3hbl6noVt9u9+z97ayFIiuzIg5XUL/kJZzNcqfAVIRDeYHiXtw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "Admin@123"
                        },
                        new
                        {
                            Id = new Guid("1a744cca-d50d-4369-8e41-3fe91db7cb1d"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ab4d3321-c80c-44c8-917d-2dcf052483f4",
                            Dob = new DateTime(2000, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "danglong@gmail.com",
                            EmailConfirmed = true,
                            FisrtName = "User",
                            LastName = "Test",
                            LockoutEnabled = false,
                            NormalizedEmail = "danglong@gmail.com",
                            NormalizedUserName = "user",
                            PasswordHash = "AQAAAAEAACcQAAAAEC7ORZ+ofNyicVrxPvyMcDKVS9+fSsHPP9ubrlOtFyi0I7xipuSky2rESJB43QJUig==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "User@123"
                        });
                });

            modelBuilder.Entity("BookStore.Data.Entities.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsShowOnHome")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("BrandId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            IsShowOnHome = true,
                            SortOrder = 1,
                            Status = 1
                        },
                        new
                        {
                            BrandId = 2,
                            IsShowOnHome = true,
                            SortOrder = 2,
                            Status = 1
                        },
                        new
                        {
                            BrandId = 3,
                            IsShowOnHome = true,
                            SortOrder = 3,
                            Status = 1
                        });
                });

            modelBuilder.Entity("BookStore.Data.Entities.BrandTranslation", b =>
                {
                    b.Property<int>("BrandTrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("LanguageId")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("SeoAlias")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("SeoDescription")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("SeoTitle")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("BrandTrId");

                    b.HasIndex("BrandId");

                    b.HasIndex("LanguageId");

                    b.ToTable("BrandTranslations");

                    b.HasData(
                        new
                        {
                            BrandTrId = 1,
                            BrandId = 1,
                            LanguageId = "vi",
                            Name = "Nhà Xuất Bản X",
                            SeoAlias = "nha-xuat-ban-x",
                            SeoDescription = "Nhà Xuất Bản X",
                            SeoTitle = "Nhà Xuất Bản X"
                        },
                        new
                        {
                            BrandTrId = 2,
                            BrandId = 2,
                            LanguageId = "vi",
                            Name = "Nhà Xuất Bản Y",
                            SeoAlias = "nha-xuat-ban-y",
                            SeoDescription = "Nhà Xuất Bản Y",
                            SeoTitle = "Nhà Xuất Bản Y"
                        },
                        new
                        {
                            BrandTrId = 3,
                            BrandId = 3,
                            LanguageId = "vi",
                            Name = "Nhà Xuất Bản Z",
                            SeoAlias = "nha-xuat-ban-z",
                            SeoDescription = "Nhà Xuất Bản Z",
                            SeoTitle = "Nhà Xuất Bản Z"
                        },
                        new
                        {
                            BrandTrId = 4,
                            BrandId = 1,
                            LanguageId = "en",
                            Name = "Publishing Company X",
                            SeoAlias = "publishing-company-x",
                            SeoDescription = "Publishing Company X",
                            SeoTitle = "Publishing Company X"
                        },
                        new
                        {
                            BrandTrId = 5,
                            BrandId = 2,
                            LanguageId = "en",
                            Name = "Publishing Company Y",
                            SeoAlias = "publishing-company-y",
                            SeoDescription = "Publishing Company Y",
                            SeoTitle = "Publishing Company Y"
                        },
                        new
                        {
                            BrandTrId = 6,
                            BrandId = 3,
                            LanguageId = "en",
                            Name = "Publishing Company Z",
                            SeoAlias = "publishing-company-z",
                            SeoDescription = "Publishing Company Z",
                            SeoTitle = "Publishing Company Z"
                        });
                });

            modelBuilder.Entity("BookStore.Data.Entities.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CartId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("BookStore.Data.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsShowOnHome")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            IsShowOnHome = true,
                            SortOrder = 1,
                            Status = 1
                        },
                        new
                        {
                            CategoryId = 2,
                            IsShowOnHome = true,
                            SortOrder = 2,
                            Status = 1
                        },
                        new
                        {
                            CategoryId = 3,
                            IsShowOnHome = true,
                            SortOrder = 3,
                            Status = 1
                        },
                        new
                        {
                            CategoryId = 4,
                            IsShowOnHome = true,
                            SortOrder = 4,
                            Status = 1
                        },
                        new
                        {
                            CategoryId = 5,
                            IsShowOnHome = true,
                            ParentId = 1,
                            SortOrder = 5,
                            Status = 1
                        },
                        new
                        {
                            CategoryId = 6,
                            IsShowOnHome = true,
                            ParentId = 1,
                            SortOrder = 6,
                            Status = 1
                        },
                        new
                        {
                            CategoryId = 7,
                            IsShowOnHome = true,
                            ParentId = 2,
                            SortOrder = 7,
                            Status = 1
                        },
                        new
                        {
                            CategoryId = 8,
                            IsShowOnHome = true,
                            ParentId = 2,
                            SortOrder = 8,
                            Status = 1
                        });
                });

            modelBuilder.Entity("BookStore.Data.Entities.CategoryTranslation", b =>
                {
                    b.Property<int>("CategoryTrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("LanguageId")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("SeoAlias")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("SeoDescription")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("SeoTitle")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("CategoryTrId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LanguageId");

                    b.ToTable("CategoryTranslations");

                    b.HasData(
                        new
                        {
                            CategoryTrId = 1,
                            CategoryId = 1,
                            LanguageId = "vi",
                            Name = "Văn Học",
                            SeoAlias = "van-hoc",
                            SeoDescription = "Văn Học",
                            SeoTitle = "Văn Học"
                        },
                        new
                        {
                            CategoryTrId = 2,
                            CategoryId = 2,
                            LanguageId = "vi",
                            Name = "Sách Học Sinh",
                            SeoAlias = "sach-hoc-sinh",
                            SeoDescription = "Sách Học Sinh",
                            SeoTitle = "Sách Học Sinh"
                        },
                        new
                        {
                            CategoryTrId = 3,
                            CategoryId = 3,
                            LanguageId = "vi",
                            Name = "Sách Ngoại Ngữ",
                            SeoAlias = "sach-ngoai-ngu",
                            SeoDescription = "Sách Ngoại Ngữ",
                            SeoTitle = "Sách Ngoại Ngữ"
                        },
                        new
                        {
                            CategoryTrId = 4,
                            CategoryId = 4,
                            LanguageId = "vi",
                            Name = "Tâm Lí - Kĩ Năng Sống",
                            SeoAlias = "tam-li-ki-nang-song",
                            SeoDescription = "Tâm Lí - Kĩ Năng Sống",
                            SeoTitle = "Tâm Lí - Kĩ Năng Sống"
                        },
                        new
                        {
                            CategoryTrId = 5,
                            CategoryId = 5,
                            LanguageId = "vi",
                            Name = "Light Novel",
                            SeoAlias = "light-novel",
                            SeoDescription = "Light Novel",
                            SeoTitle = "Light Novel"
                        },
                        new
                        {
                            CategoryTrId = 6,
                            CategoryId = 6,
                            LanguageId = "vi",
                            Name = "Tiểu Thuyết",
                            SeoAlias = "tieu-thuyet",
                            SeoDescription = "Tiểu Thuyết",
                            SeoTitle = "Tiểu Thuyết"
                        },
                        new
                        {
                            CategoryTrId = 7,
                            CategoryId = 7,
                            LanguageId = "vi",
                            Name = "Sách Giáo Khoa",
                            SeoAlias = "sach-giao-khoa",
                            SeoDescription = "Sách Giáo Khoa",
                            SeoTitle = "Sách Giáo Khoa"
                        },
                        new
                        {
                            CategoryTrId = 8,
                            CategoryId = 8,
                            LanguageId = "vi",
                            Name = "Sách Tham Khảo",
                            SeoAlias = "sach-tham-khao",
                            SeoDescription = "Sách Tham Khảo",
                            SeoTitle = "Sách Tham Khảo"
                        },
                        new
                        {
                            CategoryTrId = 9,
                            CategoryId = 1,
                            LanguageId = "en",
                            Name = "Literature",
                            SeoAlias = "literature",
                            SeoDescription = "Literature",
                            SeoTitle = "Literature"
                        },
                        new
                        {
                            CategoryTrId = 10,
                            CategoryId = 2,
                            LanguageId = "en",
                            Name = "Student Book",
                            SeoAlias = "student-book",
                            SeoDescription = "Student Book",
                            SeoTitle = "Student Book"
                        },
                        new
                        {
                            CategoryTrId = 11,
                            CategoryId = 3,
                            LanguageId = "en",
                            Name = "Foreign Book",
                            SeoAlias = "foreign-book",
                            SeoDescription = "Foreign Book",
                            SeoTitle = "Foreign Book"
                        },
                        new
                        {
                            CategoryTrId = 12,
                            CategoryId = 4,
                            LanguageId = "en",
                            Name = "Psychology - Life Skills",
                            SeoAlias = "psychology-life-skills",
                            SeoDescription = "Psychology - Life Skills",
                            SeoTitle = "Psychology - Life Skills"
                        },
                        new
                        {
                            CategoryTrId = 13,
                            CategoryId = 5,
                            LanguageId = "en",
                            Name = "Light Novel",
                            SeoAlias = "light-novel",
                            SeoDescription = "Light Novel",
                            SeoTitle = "Light Novel"
                        },
                        new
                        {
                            CategoryTrId = 14,
                            CategoryId = 6,
                            LanguageId = "en",
                            Name = "Novel",
                            SeoAlias = "novel",
                            SeoDescription = "Novel",
                            SeoTitle = "Novel"
                        },
                        new
                        {
                            CategoryTrId = 15,
                            CategoryId = 7,
                            LanguageId = "en",
                            Name = "School Book",
                            SeoAlias = "school-book",
                            SeoDescription = "School Book",
                            SeoTitle = "School Book"
                        },
                        new
                        {
                            CategoryTrId = 16,
                            CategoryId = 8,
                            LanguageId = "vi",
                            Name = "Reference Book",
                            SeoAlias = "reference-book",
                            SeoDescription = "Reference Book",
                            SeoTitle = "Reference Book"
                        });
                });

            modelBuilder.Entity("BookStore.Data.Entities.Language", b =>
                {
                    b.Property<string>("LanguageId")
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("LanguageId");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageId = "vi",
                            IsDefault = true,
                            Name = "Tiếng Việt"
                        },
                        new
                        {
                            LanguageId = "en",
                            IsDefault = false,
                            Name = "English"
                        });
                });

            modelBuilder.Entity("BookStore.Data.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShipAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("ShipEmail")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("ShipName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("ShipPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BookStore.Data.Entities.OrderDetail", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("BookStore.Data.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            DateCreated = new DateTime(2022, 6, 10, 21, 6, 12, 639, DateTimeKind.Local).AddTicks(6446),
                            IsFeatured = true,
                            OriginalPrice = 200000m,
                            Price = 210000m,
                            Stock = 10,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductId = 2,
                            DateCreated = new DateTime(2022, 6, 10, 21, 6, 12, 640, DateTimeKind.Local).AddTicks(7124),
                            IsFeatured = true,
                            OriginalPrice = 200000m,
                            Price = 210000m,
                            Stock = 10,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductId = 3,
                            DateCreated = new DateTime(2022, 6, 10, 21, 6, 12, 640, DateTimeKind.Local).AddTicks(7205),
                            IsFeatured = true,
                            OriginalPrice = 200000m,
                            Price = 210000m,
                            Stock = 10,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductId = 4,
                            DateCreated = new DateTime(2022, 6, 10, 21, 6, 12, 640, DateTimeKind.Local).AddTicks(7208),
                            IsFeatured = true,
                            OriginalPrice = 200000m,
                            Price = 210000m,
                            Stock = 10,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductId = 6,
                            DateCreated = new DateTime(2022, 6, 10, 21, 6, 12, 640, DateTimeKind.Local).AddTicks(7210),
                            IsFeatured = true,
                            OriginalPrice = 200000m,
                            Price = 210000m,
                            Stock = 10,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductId = 7,
                            DateCreated = new DateTime(2022, 6, 10, 21, 6, 12, 640, DateTimeKind.Local).AddTicks(7213),
                            IsFeatured = true,
                            OriginalPrice = 200000m,
                            Price = 210000m,
                            Stock = 10,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductId = 8,
                            DateCreated = new DateTime(2022, 6, 10, 21, 6, 12, 640, DateTimeKind.Local).AddTicks(7215),
                            IsFeatured = true,
                            OriginalPrice = 200000m,
                            Price = 210000m,
                            Stock = 10,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductId = 9,
                            DateCreated = new DateTime(2022, 6, 10, 21, 6, 12, 640, DateTimeKind.Local).AddTicks(7218),
                            IsFeatured = true,
                            OriginalPrice = 200000m,
                            Price = 210000m,
                            Stock = 10,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductId = 10,
                            DateCreated = new DateTime(2022, 6, 10, 21, 6, 12, 640, DateTimeKind.Local).AddTicks(7220),
                            IsFeatured = true,
                            OriginalPrice = 200000m,
                            Price = 210000m,
                            Stock = 10,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductId = 11,
                            DateCreated = new DateTime(2022, 6, 10, 21, 6, 12, 640, DateTimeKind.Local).AddTicks(7224),
                            IsFeatured = true,
                            OriginalPrice = 200000m,
                            Price = 210000m,
                            Stock = 10,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductId = 12,
                            DateCreated = new DateTime(2022, 6, 10, 21, 6, 12, 640, DateTimeKind.Local).AddTicks(7226),
                            IsFeatured = true,
                            OriginalPrice = 200000m,
                            Price = 210000m,
                            Stock = 10,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductId = 13,
                            DateCreated = new DateTime(2022, 6, 10, 21, 6, 12, 640, DateTimeKind.Local).AddTicks(7228),
                            IsFeatured = true,
                            OriginalPrice = 200000m,
                            Price = 210000m,
                            Stock = 10,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductId = 14,
                            DateCreated = new DateTime(2022, 6, 10, 21, 6, 12, 640, DateTimeKind.Local).AddTicks(7230),
                            IsFeatured = false,
                            OriginalPrice = 200000m,
                            Price = 210000m,
                            Stock = 10,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductId = 15,
                            DateCreated = new DateTime(2022, 6, 10, 21, 6, 12, 640, DateTimeKind.Local).AddTicks(7232),
                            IsFeatured = false,
                            OriginalPrice = 200000m,
                            Price = 210000m,
                            Stock = 10,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductId = 16,
                            DateCreated = new DateTime(2022, 6, 10, 21, 6, 12, 640, DateTimeKind.Local).AddTicks(7234),
                            IsFeatured = false,
                            OriginalPrice = 200000m,
                            Price = 210000m,
                            Stock = 10,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductId = 17,
                            DateCreated = new DateTime(2022, 6, 10, 21, 6, 12, 640, DateTimeKind.Local).AddTicks(7236),
                            IsFeatured = false,
                            OriginalPrice = 200000m,
                            Price = 210000m,
                            Stock = 10,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductId = 18,
                            DateCreated = new DateTime(2022, 6, 10, 21, 6, 12, 640, DateTimeKind.Local).AddTicks(7238),
                            IsFeatured = false,
                            OriginalPrice = 200000m,
                            Price = 210000m,
                            Stock = 10,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductId = 19,
                            DateCreated = new DateTime(2022, 6, 10, 21, 6, 12, 640, DateTimeKind.Local).AddTicks(7240),
                            IsFeatured = false,
                            OriginalPrice = 200000m,
                            Price = 210000m,
                            Stock = 10,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductId = 20,
                            DateCreated = new DateTime(2022, 6, 10, 21, 6, 12, 640, DateTimeKind.Local).AddTicks(7242),
                            IsFeatured = false,
                            OriginalPrice = 200000m,
                            Price = 210000m,
                            Stock = 10,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductId = 21,
                            DateCreated = new DateTime(2022, 6, 10, 21, 6, 12, 640, DateTimeKind.Local).AddTicks(7244),
                            IsFeatured = false,
                            OriginalPrice = 200000m,
                            Price = 210000m,
                            Stock = 10,
                            ViewCount = 0
                        },
                        new
                        {
                            ProductId = 22,
                            DateCreated = new DateTime(2022, 6, 10, 21, 6, 12, 640, DateTimeKind.Local).AddTicks(7246),
                            IsFeatured = false,
                            OriginalPrice = 200000m,
                            Price = 210000m,
                            Stock = 10,
                            ViewCount = 0
                        });
                });

            modelBuilder.Entity("BookStore.Data.Entities.ProductImage", b =>
                {
                    b.Property<int>("ProductImgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ProductImgId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("BookStore.Data.Entities.ProductInBrand", b =>
                {
                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("BrandId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductInBrands");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            BrandId = 2,
                            ProductId = 2
                        },
                        new
                        {
                            BrandId = 3,
                            ProductId = 3
                        });
                });

            modelBuilder.Entity("BookStore.Data.Entities.ProductInCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductInCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            CategoryId = 2,
                            ProductId = 2
                        },
                        new
                        {
                            CategoryId = 3,
                            ProductId = 3
                        });
                });

            modelBuilder.Entity("BookStore.Data.Entities.ProductTranslation", b =>
                {
                    b.Property<int>("ProductTrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("LanguageId")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("SeoAlias")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("SeoDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductTrId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductTranslations");

                    b.HasData(
                        new
                        {
                            ProductTrId = 1,
                            Description = "Áo sơ mi nam trắng Việt Tiến",
                            Details = "Áo sơ mi nam trắng Việt Tiến",
                            LanguageId = "vi",
                            Name = "Áo sơ mi nam trắng Việt Tiến",
                            ProductId = 1,
                            SeoAlias = "ao-so-mi-nam-trang-viet-tien",
                            SeoDescription = "Áo sơ mi nam trắng Việt Tiến",
                            SeoTitle = "Áo sơ mi nam trắng Việt Tiến"
                        },
                        new
                        {
                            ProductTrId = 2,
                            Description = "Viet Tien Men T-Shirt",
                            Details = "Viet Tien Men T-Shirt",
                            LanguageId = "en",
                            Name = "Viet Tien Men T-Shirt",
                            ProductId = 1,
                            SeoAlias = "viet-tien-men-t-shirt",
                            SeoDescription = "Viet Tien Men T-Shirt",
                            SeoTitle = "Viet Tien Men T-Shirt"
                        },
                        new
                        {
                            ProductTrId = 3,
                            Description = "Áo sơ mi nam trắng Việt Tiến",
                            Details = "Áo sơ mi nam trắng Việt Tiến",
                            LanguageId = "vi",
                            Name = "Áo sơ mi nam trắng Việt Tiến",
                            ProductId = 2,
                            SeoAlias = "ao-so-mi-nam-trang-viet-tien",
                            SeoDescription = "Áo sơ mi nam trắng Việt Tiến",
                            SeoTitle = "Áo sơ mi nam trắng Việt Tiến"
                        },
                        new
                        {
                            ProductTrId = 4,
                            Description = "Viet Tien Men T-Shirt",
                            Details = "Viet Tien Men T-Shirt",
                            LanguageId = "en",
                            Name = "Viet Tien Men T-Shirt",
                            ProductId = 2,
                            SeoAlias = "viet-tien-men-t-shirt",
                            SeoDescription = "Viet Tien Men T-Shirt",
                            SeoTitle = "Viet Tien Men T-Shirt"
                        },
                        new
                        {
                            ProductTrId = 5,
                            Description = "Áo sơ mi nam trắng Việt Tiến",
                            Details = "Áo sơ mi nam trắng Việt Tiến",
                            LanguageId = "vi",
                            Name = "Áo sơ mi nam trắng Việt Tiến",
                            ProductId = 3,
                            SeoAlias = "ao-so-mi-nam-trang-viet-tien",
                            SeoDescription = "Áo sơ mi nam trắng Việt Tiến",
                            SeoTitle = "Áo sơ mi nam trắng Việt Tiến"
                        },
                        new
                        {
                            ProductTrId = 6,
                            Description = "Viet Tien Men T-Shirt",
                            Details = "Viet Tien Men T-Shirt",
                            LanguageId = "en",
                            Name = "Viet Tien Men T-Shirt",
                            ProductId = 3,
                            SeoAlias = "viet-tien-men-t-shirt",
                            SeoDescription = "Viet Tien Men T-Shirt",
                            SeoTitle = "Viet Tien Men T-Shirt"
                        });
                });

            modelBuilder.Entity("BookStore.Data.Entities.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ApplyForAll")
                        .HasColumnType("bit");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductCategoryIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("BookStore.Data.Entities.Slide", b =>
                {
                    b.Property<int>("SlideId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("SlideId");

                    b.ToTable("Slides");

                    b.HasData(
                        new
                        {
                            SlideId = 1,
                            Description = "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.",
                            Image = "/themes/images/carousel/1.png",
                            Name = "Second Thumbnail label",
                            SortOrder = 1,
                            Status = 1,
                            Url = "#"
                        },
                        new
                        {
                            SlideId = 2,
                            Description = "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.",
                            Image = "/themes/images/carousel/2.png",
                            Name = "Second Thumbnail label",
                            SortOrder = 2,
                            Status = 1,
                            Url = "#"
                        },
                        new
                        {
                            SlideId = 3,
                            Description = "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.",
                            Image = "/themes/images/carousel/3.png",
                            Name = "Second Thumbnail label",
                            SortOrder = 3,
                            Status = 1,
                            Url = "#"
                        },
                        new
                        {
                            SlideId = 4,
                            Description = "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.",
                            Image = "/themes/images/carousel/4.png",
                            Name = "Second Thumbnail label",
                            SortOrder = 4,
                            Status = 1,
                            Url = "#"
                        },
                        new
                        {
                            SlideId = 5,
                            Description = "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.",
                            Image = "/themes/images/carousel/5.png",
                            Name = "Second Thumbnail label",
                            SortOrder = 5,
                            Status = 1,
                            Url = "#"
                        },
                        new
                        {
                            SlideId = 6,
                            Description = "Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.",
                            Image = "/themes/images/carousel/6.png",
                            Name = "Second Thumbnail label",
                            SortOrder = 6,
                            Status = 1,
                            Url = "#"
                        });
                });

            modelBuilder.Entity("BookStore.Data.Entities.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ExternalTransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("AppUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("1cee3d50-87bb-48d5-a493-376829c581c9"),
                            RoleId = new Guid("d4965cc8-fdab-433f-ae1d-79540827db5a")
                        },
                        new
                        {
                            UserId = new Guid("1a744cca-d50d-4369-8e41-3fe91db7cb1d"),
                            RoleId = new Guid("90057ee3-511a-4de1-94c2-93898f1018d9")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserTokens");
                });

            modelBuilder.Entity("BookStore.Data.Entities.BrandTranslation", b =>
                {
                    b.HasOne("BookStore.Data.Entities.Brand", "Brand")
                        .WithMany("BrandTranslations")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore.Data.Entities.Language", "Language")
                        .WithMany("BrandTranslations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookStore.Data.Entities.Cart", b =>
                {
                    b.HasOne("BookStore.Data.Entities.Product", "Product")
                        .WithMany("Carts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore.Data.Entities.AppUser", "AppUser")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookStore.Data.Entities.CategoryTranslation", b =>
                {
                    b.HasOne("BookStore.Data.Entities.Category", "Category")
                        .WithMany("CategoryTranslations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore.Data.Entities.Language", "Language")
                        .WithMany("CategoryTranslations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookStore.Data.Entities.Order", b =>
                {
                    b.HasOne("BookStore.Data.Entities.AppUser", "AppUser")
                        .WithMany("Oders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookStore.Data.Entities.OrderDetail", b =>
                {
                    b.HasOne("BookStore.Data.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore.Data.Entities.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookStore.Data.Entities.ProductImage", b =>
                {
                    b.HasOne("BookStore.Data.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookStore.Data.Entities.ProductInBrand", b =>
                {
                    b.HasOne("BookStore.Data.Entities.Brand", "Brand")
                        .WithMany("ProductInBrands")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore.Data.Entities.Product", "Product")
                        .WithMany("ProductInBrands")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookStore.Data.Entities.ProductInCategory", b =>
                {
                    b.HasOne("BookStore.Data.Entities.Category", "Category")
                        .WithMany("ProductInCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore.Data.Entities.Product", "Product")
                        .WithMany("ProductInCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookStore.Data.Entities.ProductTranslation", b =>
                {
                    b.HasOne("BookStore.Data.Entities.Language", "Language")
                        .WithMany("ProductTranslations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStore.Data.Entities.Product", "Product")
                        .WithMany("ProductTranslations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookStore.Data.Entities.Transaction", b =>
                {
                    b.HasOne("BookStore.Data.Entities.AppUser", "AppUser")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
